/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['body[_ngcontent-%COMP%] {\r\n  padding: 50px;\r\n  font: 14px "Lucida Grande", Helvetica, Arial, sans-serif;\r\n}\r\nh1[_ngcontent-%COMP%]{\r\n  color: red;\r\n}'];